--itemstrings.lua
STRINGS.CHARACTER_TITLES.will = "The Bumpkin Farmer"
STRINGS.CHARACTER_NAMES.will = "Willoughby"
STRINGS.CHARACTER_DESCRIPTIONS.will = "*Vegetarian\n*Cursed child\n*Doesn't hit hard"
STRINGS.CHARACTER_QUOTES.will = "\"Same out here as it was at home!\""
STRINGS.CHARACTER_TITLES.windell = "The Mountie"
STRINGS.CHARACTER_NAMES.windell = "Windell"
STRINGS.CHARACTER_DESCRIPTIONS.windell = "*Remembers landmarks\n*perk2\n*perk3"
STRINGS.CHARACTER_QUOTES.windell = "\"Quote\""
STRINGS.CHARACTER_TITLES.doc = "The Gentleman Scientist"
STRINGS.CHARACTER_NAMES.doc = "Doctor Higgsbury"
STRINGS.CHARACTER_DESCRIPTIONS.doc = "*Grows a magnificent beard\n*Has pharmaceutical knowledge"
STRINGS.CHARACTER_QUOTES.doc = "\"I want to help you.\""
STRINGS.NAMES.WILL = "Willoughby"
STRINGS.NAMES.WINDELL = "Windell"
STRINGS.NAMES.DOC = "Dr.Higgsbury"
GLOBAL.STRINGS.NAMES.BUMPKINFARM = "Bumpkin Farm"
STRINGS.RECIPE_DESC.BUMPKINFARM = "Insulated for hot and cold temperatures!"
--POTIONS
GLOBAL.STRINGS.NAMES.GREEN_POTION = "Green Medicine"
STRINGS.RECIPE_DESC.GREEN_POTION = "Treats therianthropy and insanity."
GLOBAL.STRINGS.NAMES.ELIXIR = "Elixir"
STRINGS.RECIPE_DESC.ELIXIR = "Mild painkiller and all-purpose healer."
GLOBAL.STRINGS.NAMES.ORANGE_POTION = "Bottled Lightning"
GLOBAL.STRINGS.NAMES.YELLOW_POTION = "10 Second Energy"
GLOBAL.STRINGS.NAMES.FIRE_POTION = "Warm-Me-Up"
STRINGS.RECIPE_DESC.YELLOW_POTION = "A really quick speed boost."
STRINGS.RECIPE_DESC.ORANGE_POTION = "Zap!"
STRINGS.RECIPE_DESC.FIRE_POTION = "Relieves hypothermia."
GLOBAL.STRINGS.NAMES.ICE_POTION = "Fever Reducer"
STRINGS.RECIPE_DESC.ICE_POTION = "Lowers temperature."

---
GLOBAL.STRINGS.NAMES.CHEAPBERRYBUSH = "Raspberry Bush"
STRINGS.RECIPE_DESC.CHEAPBERRYBUSH = "Grow some emergency food."
STRINGS.RECIPE_DESC.BBQ = "For cooking in the summer!"


--For the North!
GLOBAL.STRINGS.NAMES.LOON = "Loon"
GLOBAL.STRINGS.NAMES.FEATHER_LOON = "Loon Feather"
GLOBAL.STRINGS.NAMES.DREAM_CATCHER = "Dream Catcher"
STRINGS.RECIPE_DESC.DREAM_CATCHER = "It's not wise to sleep with it every night..."
GLOBAL.STRINGS.NAMES.SAP = "Birchnut Sap"
GLOBAL.STRINGS.NAMES.MAPLESYRUP = "Birchnut Syrup"
GLOBAL.STRINGS.NAMES.LEAF = "Birchnut Leaf"
GLOBAL.STRINGS.NAMES.MAPLELANTERN = "Leaf Lantern"
GLOBAL.STRINGS.NAMES.MAPLEPOP = "Maple Sucker"
GLOBAL.STRINGS.NAMES.POPSPEAR = "Maple Spear"
GLOBAL.STRINGS.NAMES.PUMPKINPIE = "Pumpkin Pie"
GLOBAL.STRINGS.NAMES.BBQ = "Barbeque Grill"
GLOBAL.STRINGS.NAMES.RASPBERRYBUSH = "Raspberry Bush"